CREATE SCHEMA public;

CREATE TABLE NOC(
	NOCcode VARCHAR NOT NULL,
	NOCDesc VARCHAR NOT NULL,
	PRIMARY KEY (NOCcode)
);

CREATE TABLE AverageWage(
	WageID INT NOT NULL,
	RefDate DATE NOT NULL,
	Location VARCHAR NOT NULL,
	NOCcode VARCHAR NOT NULL,
	JobDetails VARCHAR NOT NULL,
	AvgWage VARCHAR NOT NULL,
	PRIMARY KEY (WageID),
	FOREIGN KEY (NOCcode) REFERENCES NOC (NOCcode)
);

CREATE TABLE Vacancies (
	VacancyID INT NOT NULL,
	RefDate DATE NOT NULL,
	Location VARCHAR NOT NULL,
	NOCcode VARCHAR NOT NULL,
	JobDetails VARCHAR NOT NULL,
	NoOfVacancies INT NOT NULL,
	PRIMARY KEY (VacancyID),
	FOREIGN KEY (NOCcode) REFERENCES NOC (NOCcode)
);

CREATE TABLE VacancyRequirements(
	RequirementID INT NOT NULL,
	RefDate DATE NOT NULL,
	Location VARCHAR NOT NULL,
	NOCcode VARCHAR NOT NULL,
	JobDetails VARCHAR NOT NULL,
	TotalPercent INT NOT NULL,
	PRIMARY KEY (RequirementID),
	FOREIGN KEY (NOCcode) REFERENCES NOC (NOCcode)
);

CREATE TABLE AvgNOCWage(
	NOCcode VARCHAR NOT NULL,
	RefDate DATE NOT NULL,
	AvgWage FLOAT NOT NULL,
	FOREIGN KEY (NOCcode) REFERENCES NOC (NOCcode),
	PRIMARY KEY (NOCcode)
);

CREATE TABLE TotalNOCVacancies(
	NOCcode VARCHAR NOT NULL,
	RefDate DATE NOT NULL,
	TotalVacancies INT NOT NULL,
	FOREIGN KEY (NOCcode) REFERENCES NOC (NOCcode),
	PRIMARY KEY (NOCcode)
);